apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: registry
  name: registry
spec:
  containers:
  - image: docker.io/library/registry
    name: registry
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: registry
  name: registry
spec:
  ports:
  - name: registry
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=./Containerfile"
    - "--context=git://github.com/jbertozzi/fling-xvm"
    - "--destination=registry.default.svc.cluster.local/fling-xvm"
  restartPolicy: Never
